### PR TITLE
[WIP] Update to bigtable 0.29.0

### PR DESCRIPTION
**Pull request by theacodes**
Towards #33

### CODE REVIEW

**Comment by jonparrott** [comment]
@tseaver I need some help on this. I am a bit unclear on the bigtable API changes but I got most things to work, however, the system tests are now getting bytes for things where before it didn't expect them. I don't know if the issue is with this library or bigtable. Can you take over this from here?

Example:

```
======================================================================
FAIL: test_scan_single_row (happybase.TestTable_scan)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jonwayne/workspace/google-cloud-python-happybase/system_tests/happybase.py", line 473, in test_scan_single_row
    self.assertEqual(scan_result, [(ROW_KEY1, row1_data)])
AssertionError: Lists differ: [(b'row-key1', {b'cf1:qual1': b'value1', b'cf1:qual2': b'value2'})] != [(b'row-key1', {'cf1:qual1': b'value1', 'cf1:qual2': b'value2'})]

First differing element 0:
(b'row-key1', {b'cf1:qual1': b'value1', b'cf1:qual2': b'value2'})
(b'row-key1', {'cf1:qual1': b'value1', 'cf1:qual2': b'value2'})

- [(b'row-key1', {b'cf1:qual1': b'value1', b'cf1:qual2': b'value2'})]
?                 -                        -

+ [(b'row-key1', {'cf1:qual1': b'value1', 'cf1:qual2': b'value2'})]
```

**Comment by Froskekongen** [comment]
@theacodes: Are you planning to finish this PR? It would be a great boon!

**Comment by theacodes** [comment]
@sduskis can you take this on?

**Comment by sduskis** [comment]
@theacodes, I'm already on it :)

**Comment by theacodes** [comment]
You rock! :)

**Comment by Froskekongen** [comment]
Would be great to have this fixed and a new release on pypi. I am using pipenv cloning directly from this repository, but a proper release would be much better.

**Comment by sduskis** [comment]
@theacodes, can you please close this PR?  This was fixed with #37.

**Pull request closed without merging**
