### PR TITLE
Set bounds for google-cloud-bigtable dependency.

### PR DESCRIPTION
**Pull request by daspecster**
This sets the dependency boundaries for `google-cloud-bigtable` in setup.py.

### CODE REVIEW

**Comment by dhermes** [comment]
You probably want to rev the version as well?

**Comment by daspecster** [comment]
I can't merge this FYI.

**Comment by dhermes** [comment]
Got it. Thanks for the heads up. I wonder why

**Comment by daspecster** [comment]
It's a different repo and I don't have org permissions.

**Pull request merged**
